name: BruteforceApple
options:
  bundleIdPrefix: com.amerhwitat
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
targets:
  BruteforceApple:
    type: application
    platform: iOS
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amerhwitat.bruteforce
        GENERATE_INFOPLIST_FILE: YES
  BruteforceMac:
    type: application
    platform: macOS
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amerhwitat.bruteforce.mac
        GENERATE_INFOPLIST_FILE: YES
